condition_translations = {
    "Sunny": "Солнечно",
    "Clear": "Ясно",
    "Partly cloudy": "Переменная облачность",
    "Cloudy": "Облачно",
    "Overcast": "Пасмурно",
    "Mist": "Туман",
    "Patchy rain possible": "Возможен небольшой дождь",
    "Patchy snow possible": "Возможен небольшой снег",
    "Patchy sleet possible": "Возможен небольшой дождь со снегом",
    "Patchy freezing drizzle possible": "Возможно небольшое замерзающее морось",
    "Thundery outbreaks possible": "Местами грозы",
    "Blowing snow": "Снегопад",
    "Blizzard": "Метель",
    "Fog": "Туман",
    "Freezing fog": "Морозный туман",
    "Patchy light drizzle": "Небольшой моросящий дождь",
    "Light drizzle": "Небольшой дождь",
    "Freezing drizzle": "Замерзающий дождь",
    "Heavy freezing drizzle": "Сильный замерзающий дождь",
    "Patchy light rain": "Небольшой дождь",
    "Light rain": "Легкий дождь",
    "Moderate rain at times": "Временами умеренный дождь",
    "Moderate rain": "Умеренный дождь",
    "Heavy rain at times": "Временами сильный дождь",
    "Heavy rain": "Сильный дождь",
    "Light freezing rain": "Легкий замерзающий дождь",
    "Moderate or heavy freezing rain": "Умеренный или сильный замерзающий дождь",
    "Light sleet": "Легкий дождь со снегом",
    "Moderate or heavy sleet": "Умеренный или сильный дождь со снегом",
    "Patchy light snow": "Небольшой снег",
    "Light snow": "Легкий снег",
    "Patchy moderate snow": "Умеренный снег",
    "Moderate snow": "Умеренный снег",
    "Patchy heavy snow": "Сильный снег",
    "Heavy snow": "Сильный снег",
    "Ice pellets": "Ледяные крупинки",
    "Light rain shower": "Небольшой ливень",
    "Moderate or heavy rain shower": "Умеренный или сильный ливень",
    "Torrential rain shower": "Ливень",
    "Light sleet showers": "Небольшие дождь со снегом",
    "Moderate or heavy sleet showers": "Умеренные или сильные дождь со снегом",
    "Light snow showers": "Небольшой снегопад",
    "Moderate or heavy snow showers": "Умеренный или сильный снегопад"
}